# Generated by Django 2.0 on 2020-10-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20201028_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
