# Generated by Django 2.0 on 2020-10-28 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20201028_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 28, 11, 3, 7, 924709)),
        ),
    ]
