# Generated by Django 2.0 on 2020-10-28 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20201028_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idArea', models.AutoField(primary_key=True, serialize=False)),
                ('unArea', models.IntegerField(blank=True, default=0, null=True)),
                ('unBranchCommi', models.IntegerField(blank=True, default=0, null=True)),
                ('AName', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('ASAPSvr', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ASAPDB', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('ASAPUsr', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('ASAPPwd', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ASAPDataSource', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('TimeStamp', models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 28, 16, 6, 59, 137551))),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 28, 16, 6, 59, 137551)),
        ),
    ]
