# Generated by Django 2.0 on 2020-11-03 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20201028_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateItemControl',
            fields=[
                ('idTemplateItemControl', models.AutoField(primary_key=True, serialize=False)),
                ('unTemplateItemControl', models.IntegerField(blank=True, default=0, null=True)),
                ('unArea', models.IntegerField(blank=True, default=0, null=True)),
                ('TICName', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('TimeStamp', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 10, 57, 16, 244218))),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 10, 57, 16, 244218)),
        ),
        migrations.AlterField(
            model_name='area',
            name='unBranchCommi',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 10, 57, 16, 244218)),
        ),
    ]
