# Generated by Django 2.0 on 2021-01-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20201103_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='templateitemcontrol',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
