# Generated by Django 2.0 on 2021-01-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20210104_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('idAccountGroup', models.AutoField(primary_key=True, serialize=False)),
                ('AGName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('idAccountUser', models.AutoField(primary_key=True, serialize=False)),
                ('idAccountGroup', models.IntegerField(blank=True, default=0, null=True)),
                ('idArea', models.IntegerField(blank=True, default=0, null=True)),
                ('unAccountUser', models.IntegerField(blank=True, default=0, null=True)),
                ('AUUserName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('AULastName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('AUFirstName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('AUMiddleName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('AUPassword', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('AUEmail', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('AGName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('AName', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('AUSession', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='unArea',
            new_name='fkArea',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='unBranch',
            new_name='fkTemplateItemControl',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='unTemplateItemControl',
            new_name='fkTemplateProductionBatch',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='unTemplateProductionBatch',
        ),
        migrations.AddField(
            model_name='branch',
            name='AName',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='TICName',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='TPBName',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='BType',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
