# Generated by Django 2.0 on 2020-11-10 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20201110_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='unArea',
            new_name='fkArea',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='unBranch',
            new_name='fkTIC',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='unTemplateItemControl',
            new_name='fkTPB',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='unTemplateProductionBatch',
        ),
        migrations.AddField(
            model_name='branch',
            name='AName',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='TICName',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='TPBName',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 5, 40, 742740)),
        ),
        migrations.AlterField(
            model_name='branch',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 5, 40, 742740)),
        ),
        migrations.AlterField(
            model_name='templateitemcontrol',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 5, 40, 742740)),
        ),
        migrations.AlterField(
            model_name='templateproductionbatch',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 5, 40, 742740)),
        ),
    ]
