# Generated by Django 2.0 on 2021-01-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20210112_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='AName',
        ),
    ]
