# Generated by Django 2.0 on 2020-11-10 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20201110_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='fkTIC',
            new_name='fkTemplateItemControl',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='fkTPB',
            new_name='fkTemplateProductionBatch',
        ),
        migrations.RenameField(
            model_name='templateproductionbatch',
            old_name='fkTIC',
            new_name='fkTemplateItemControl',
        ),
        migrations.AlterField(
            model_name='area',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 14, 12, 68311)),
        ),
        migrations.AlterField(
            model_name='branch',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 14, 12, 68311)),
        ),
        migrations.AlterField(
            model_name='templateitemcontrol',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 14, 12, 68311)),
        ),
        migrations.AlterField(
            model_name='templateproductionbatch',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 14, 12, 68311)),
        ),
    ]
