# Generated by Django 2.0 on 2021-01-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_remove_accountuser_aname'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='AName',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
