# Generated by Django 2.0 on 2020-11-10 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20201110_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 33, 57, 546765)),
        ),
        migrations.AlterField(
            model_name='branch',
            name='BType',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 33, 57, 531114)),
        ),
        migrations.AlterField(
            model_name='templateitemcontrol',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 33, 57, 546765)),
        ),
        migrations.AlterField(
            model_name='templateproductionbatch',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 15, 33, 57, 546765)),
        ),
    ]
