# Generated by Django 2.0 on 2021-01-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_accountuser_aname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUserArea',
            fields=[
                ('idAccountUserArea', models.AutoField(primary_key=True, serialize=False)),
                ('idAccountUser', models.IntegerField(blank=True, default=0, null=True)),
                ('idArea', models.IntegerField(blank=True, default=0, null=True)),
                ('AName', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='AName',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='idArea',
        ),
    ]
