# Generated by Django 2.0 on 2021-02-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20210118_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('idEmployeeGroup', models.AutoField(primary_key=True, serialize=False)),
                ('EGName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('EGLevel', models.DateTimeField(auto_now_add=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
