# Generated by Django 2.0.7 on 2021-02-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20210201_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUOM',
            fields=[
                ('idProductUOM', models.AutoField(primary_key=True, serialize=False)),
                ('PUOMName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
