# Generated by Django 2.0 on 2021-02-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_discounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounttype',
            name='DTVatExempt',
            field=models.BooleanField(default=False),
        ),
    ]
