# Generated by Django 2.0 on 2021-02-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20210209_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('idPaymentType', models.AutoField(primary_key=True, serialize=False)),
                ('PTName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('PTFixedAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('PTReference', models.IntegerField(default=0)),
                ('PTPriority', models.IntegerField(default=0)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
