# Generated by Django 2.0 on 2021-02-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='AName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='BName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
