# Generated by Django 2.0.7 on 2021-02-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_auto_20210216_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idEmployee', models.AutoField(primary_key=True, serialize=False)),
                ('idEmployeeGroup', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('unEmployee', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('ELastName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('EFirstName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('EMiddleName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('EAlias', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ENumber', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('EUsername', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('EPassword', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
