# Generated by Django 2.0.7 on 2021-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0021_employee_egroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='idEmployeeGroup',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
