# Generated by Django 2.0 on 2021-02-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0022_auto_20210222_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccountArea',
            fields=[
                ('idEmployeeAccountArea', models.AutoField(primary_key=True, serialize=False)),
                ('idEmployee', models.IntegerField(blank=True, default=0, null=True)),
                ('idArea', models.IntegerField(blank=True, default=0, null=True)),
                ('AName', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
