# Generated by Django 2.0 on 2021-03-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0023_employeeaccountarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('idProductGroup', models.AutoField(primary_key=True, serialize=False)),
                ('idProductType', models.IntegerField(default=0)),
                ('idShortageType', models.IntegerField(default=0)),
                ('PTName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('STName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('PGName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('PGPriority', models.IntegerField(default=0)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('idProductType', models.AutoField(primary_key=True, serialize=False)),
                ('PTName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortageType',
            fields=[
                ('idShortageType', models.AutoField(primary_key=True, serialize=False)),
                ('STName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
