# Generated by Django 2.0 on 2021-03-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0024_productgroup_producttype_shortagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('idProductItem', models.AutoField(primary_key=True, serialize=False)),
                ('idProductUOM', models.IntegerField(default=0)),
                ('idProductGroup', models.IntegerField(default=0)),
                ('PIName', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('PISAPCode', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('PIPack', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('PIBulkDiscount', models.IntegerField(default=0)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
