# Generated by Django 2.0 on 2021-03-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0025_productitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='PGName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='PUOMName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
